### ISSUE TITLE
Things that need doing

### ISSUE THREAD

**Issue by eric79** [virtual-world-framework/vwf-web#3]
- Server bits
  - [x] Serve page from a static web page server that can handle https
  - [x] Install external certs
  - [x] Bootstrap new server to serve the page
  - [x] Have http redirect to https and have all iframes be https
  - [x] Set up certs on demo.virtual.wf
  - [x] The documentation links were updated to use https://demo.virtualworldframework.com. I missed two on the NY / San Fran duck example that need to be updated. If this https fix allows for virtual.wf to work, then all demo links will need to be updated as well. (PR #20)
  - [x] Delete PR #9 and associated branch, if appropriate
- Main page
  - [x] When Windows is detected, display Download button that downloads Windows installer
  - [x] Fix key movement in Firefox (PR #5)
  - [x] Fix aspect ratio of pong - @allisoncorey and @jessmartin, I'm looking for advice on this one.  Cross-domain restrictions have me stymied.
  - [x] Work on pixelated fonts on Windows
  - [x] Fix platform recognition (currently it shows Windows installer on Ubuntu)
  - [x] Augment Collaborative sentence
  - [x] Capitalize "H" in "GitHub" in all places it is referenced (at least 2)
  - [x] Share VWF Pong link does not contain the app name. 
- Demos
  - [x] Fix spacing – change to bootstrap grid layout
  - [x] Get “Current sessions” functionality working
  - [x] Fix unhandled exception in preparePongFrame when navigating to demos page
- Documentation
  - [x] Test Windows installer
    - Does it open directions when its done installing?
    - Does vwf create and vwf work?
  - [x] Fix spacing – change to bootstrap grid layout
  - [x] Pull updated Installation Instructions into documentation page
- [x] Fix all links
- Downloads
  - [x] Update font and colors to match the rest of the website
  - [x] Get rid of scroll bar on iframe, either by elongating the iframe, or removing old build links from the page. 
- Layout
  - [x] Remove editor from pong app to get rid of the scroll bars
  - [x] Fix mobile layout
- [x] Detect when Javascript, WebSockets, or WebGL are not enabled and display appropriate helpful error message (PR #11)
- [x] Detect when Javascript is not ECMAScript 5 or greater
- [x] Have app detect when network squashes WebSocket connection and display appropriate message
- [x] Test site in every browser/platform - anything that needs improvement?
- [x] Deploy to virtual.wf
- [x] Tell our friends at Z-Shift where they can see our new website so they can give us feedback
- [x] Remove unsupported.html
- [x] Suggestion: the VWF readme is pointing to the old website forum page. Since this website will be going away, we should update the forum link to go directly to the forum (http://forum.virtualworldframework.com/) rather than the page embedding an iframe to the forum until StackOverflow support is added.
